### ISSUE TITLE
Unable to start tendrl-api using client CA certificates in SSLConnection

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/api#317] opened 2017-10-11 19:56 UTC
Oct 11 19:44:47 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Started Tendrl Api Daemon.
Oct 11 19:44:47 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Starting Tendrl Api Daemon...
Oct 11 19:44:48 dhcp42-122.lab.eng.blr.redhat.com puma[11306]: [11306] Puma starting in cluster mode...
Oct 11 19:44:48 dhcp42-122.lab.eng.blr.redhat.com puma[11306]: [11306] * Version 3.6.0 (ruby 2.0.0-p648), codename: Sleepy Sunday Serenity
Oct 11 19:44:48 dhcp42-122.lab.eng.blr.redhat.com puma[11306]: [11306] * Min threads: 8, max threads: 8
Oct 11 19:44:48 dhcp42-122.lab.eng.blr.redhat.com puma[11306]: [11306] * Environment: production
Oct 11 19:44:48 dhcp42-122.lab.eng.blr.redhat.com puma[11306]: [11306] * Process workers: 2
Oct 11 19:44:48 dhcp42-122.lab.eng.blr.redhat.com puma[11306]: [11306] * Preloading application
Oct 11 19:44:48 dhcp42-122.lab.eng.blr.redhat.com puma[11306]: [11306] * Listening on tcp://127.0.0.1:9292
Oct 11 19:44:48 dhcp42-122.lab.eng.blr.redhat.com puma[11306]: [11306] Use Ctrl-C to stop
Oct 11 20:45:03 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Stopping Tendrl Api Daemon...
Oct 11 20:45:03 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Stopped Tendrl Api Daemon.
Oct 11 23:56:56 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Started Tendrl Api Daemon.
Oct 11 23:56:56 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Starting Tendrl Api Daemon...
Oct 11 23:56:56 dhcp42-122.lab.eng.blr.redhat.com puma[3749]: [3749] Puma starting in cluster mode...
Oct 11 23:56:56 dhcp42-122.lab.eng.blr.redhat.com puma[3749]: [3749] * Version 3.6.0 (ruby 2.0.0-p648), codename: Sleepy Sunday Serenity
Oct 11 23:56:56 dhcp42-122.lab.eng.blr.redhat.com puma[3749]: [3749] * Min threads: 8, max threads: 8
Oct 11 23:56:56 dhcp42-122.lab.eng.blr.redhat.com puma[3749]: [3749] * Environment: production
Oct 11 23:56:56 dhcp42-122.lab.eng.blr.redhat.com puma[3749]: [3749] * Process workers: 2
Oct 11 23:56:56 dhcp42-122.lab.eng.blr.redhat.com puma[3749]: [3749] * Preloading application
Oct 11 23:56:56 dhcp42-122.lab.eng.blr.redhat.com puma[3749]: [3749] * Listening on tcp://127.0.0.1:9292
Oct 11 23:56:56 dhcp42-122.lab.eng.blr.redhat.com puma[3749]: [3749] Use Ctrl-C to stop
Oct 11 23:56:57 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Stopping Tendrl Api Daemon...
Oct 11 23:56:57 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Started Tendrl Api Daemon.
Oct 11 23:56:57 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Starting Tendrl Api Daemon...
Oct 11 23:56:58 dhcp42-122.lab.eng.blr.redhat.com puma[3801]: [3801] Puma starting in cluster mode...
Oct 11 23:56:58 dhcp42-122.lab.eng.blr.redhat.com puma[3801]: [3801] * Version 3.6.0 (ruby 2.0.0-p648), codename: Sleepy Sunday Serenity
Oct 11 23:56:58 dhcp42-122.lab.eng.blr.redhat.com puma[3801]: [3801] * Min threads: 8, max threads: 8
Oct 11 23:56:58 dhcp42-122.lab.eng.blr.redhat.com puma[3801]: [3801] * Environment: production
Oct 11 23:56:58 dhcp42-122.lab.eng.blr.redhat.com puma[3801]: [3801] * Process workers: 2
Oct 11 23:56:58 dhcp42-122.lab.eng.blr.redhat.com puma[3801]: [3801] * Preloading application
Oct 11 23:56:58 dhcp42-122.lab.eng.blr.redhat.com puma[3801]: [3801] * Listening on tcp://127.0.0.1:9292
Oct 11 23:56:58 dhcp42-122.lab.eng.blr.redhat.com puma[3801]: [3801] Use Ctrl-C to stop
Oct 11 23:56:59 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Stopping Tendrl Api Daemon...
Oct 11 23:56:59 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Started Tendrl Api Daemon.
Oct 11 23:56:59 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Starting Tendrl Api Daemon...
Oct 11 23:56:59 dhcp42-122.lab.eng.blr.redhat.com puma[3863]: [3863] Puma starting in cluster mode...
Oct 11 23:56:59 dhcp42-122.lab.eng.blr.redhat.com puma[3863]: [3863] * Version 3.6.0 (ruby 2.0.0-p648), codename: Sleepy Sunday Serenity
Oct 11 23:56:59 dhcp42-122.lab.eng.blr.redhat.com puma[3863]: [3863] * Min threads: 8, max threads: 8
Oct 11 23:56:59 dhcp42-122.lab.eng.blr.redhat.com puma[3863]: [3863] * Environment: production
Oct 11 23:56:59 dhcp42-122.lab.eng.blr.redhat.com puma[3863]: [3863] * Process workers: 2
Oct 11 23:56:59 dhcp42-122.lab.eng.blr.redhat.com puma[3863]: [3863] * Preloading application
Oct 11 23:57:00 dhcp42-122.lab.eng.blr.redhat.com puma[3863]: [3863] * Listening on tcp://127.0.0.1:9292
Oct 11 23:57:00 dhcp42-122.lab.eng.blr.redhat.com puma[3863]: [3863] Use Ctrl-C to stop
Oct 11 23:57:00 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Stopping Tendrl Api Daemon...
Oct 11 23:57:00 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Started Tendrl Api Daemon.
Oct 11 23:57:00 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Starting Tendrl Api Daemon...
...skipping...
Oct 12 00:54:25 dhcp42-122.lab.eng.blr.redhat.com puma[8401]: from /usr/share/gems/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
Oct 12 00:54:25 dhcp42-122.lab.eng.blr.redhat.com puma[8401]: from /usr/share/gems/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
Oct 12 00:54:25 dhcp42-122.lab.eng.blr.redhat.com puma[8401]: from /usr/bin/puma:23:in `load'
Oct 12 00:54:25 dhcp42-122.lab.eng.blr.redhat.com puma[8401]: from /usr/bin/puma:23:in `<main>'
Oct 12 00:54:25 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: tendrl-api.service: main process exited, code=exited, status=1/FAILURE
Oct 12 00:54:25 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Unit tendrl-api.service entered failed state.
Oct 12 00:54:25 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: tendrl-api.service failed.
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: tendrl-api.service holdoff time over, scheduling restart.
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Started Tendrl Api Daemon.
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Starting Tendrl Api Daemon...
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: [8406] Puma starting in cluster mode...
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: [8406] * Version 3.6.0 (ruby 2.0.0-p648), codename: Sleepy Sunday Serenity
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: [8406] * Min threads: 8, max threads: 8
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: [8406] * Environment: production
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: [8406] * Process workers: 2
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: [8406] * Preloading application
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: [8406] ! Unable to load application: NoMethodError: undefined method `load_cert_config' for main:Object
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: /usr/share/tendrl-api/config/initializers/etcd.rb:6:in `<top (required)>': undefined method `load_cert_config' 
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/tendrl-api/lib/tendrl.rb:93:in `<top (required)>'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from config.ru:3:in `block in <main>'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from config.ru:in `new'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from config.ru:in `<main>'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/gems/gems/puma-3.6.0/lib/puma/configuration.rb:315:in `load_rackup'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/gems/gems/puma-3.6.0/lib/puma/configuration.rb:243:in `app'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/gems/gems/puma-3.6.0/lib/puma/runner.rb:127:in `load_and_bind'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/gems/gems/puma-3.6.0/lib/puma/cluster.rb:370:in `run'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/gems/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/gems/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/share/gems/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/bin/puma:23:in `load'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com puma[8406]: from /usr/bin/puma:23:in `<main>'
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: tendrl-api.service: main process exited, code=exited, status=1/FAILURE
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Unit tendrl-api.service entered failed state.
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: tendrl-api.service failed.
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: tendrl-api.service holdoff time over, scheduling restart.
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: start request repeated too quickly for tendrl-api.service
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Failed to start Tendrl Api Daemon.
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: Unit tendrl-api.service entered failed state.
Oct 12 00:54:26 dhcp42-122.lab.eng.blr.redhat.com systemd[1]: tendrl-api.service failed.

**Comment by GowthamShanmugam** [comment] 2017-10-11 19:57
@anivargi @r0h4n @nthomas-redhat

**Comment by mbukatov** [comment] 2017-10-12 07:21
We need to find out whether this error have a different root cause compared to the issue which I shared yesterday on tendrl-devel channel.

**Comment by anivargi** [comment] 2017-10-12 08:52
Fixed in https://github.com/Tendrl/api/pull/318

**Closed by anivargi** 2017-10-12 08:52 UTC
Labels: API, bug
