### ISSUE TITLE
Volume names missing in response to api call clusters/<CLUSTERID>/volumes

### ISSUE THREAD

**Issue by dahorak** [Tendrl/api#324] opened 2017-10-17 08:03 UTC
Sometime volume name is not visible in the list of volumes in Tendrl web UI and also not present in the response to API call `clusters/<CLUSTERID>/volumes`.

![tendrl_cluster_volumes_missing_volume_name](https://user-images.githubusercontent.com/4759779/31652840-d0cd13d2-b320-11e7-968e-7c9fd241e3e1.png)

```GET http://server.example.com/api/1.0/clusters/12353d78-fe6a-42dc-827a-ff887c0a2802/volumes```
```
{
  "volumes": [
    {
      "updated_at": "2017-10-17 07:52:43.736472+00:00",
      "rebalancedetails": {
        "0bd5aee3-08a3-42bd-b00f-634c3d7c4527": {
          "hash": "495c844473354686b9f60fe4569998ca",
          "rebal_files": "0",
          "rebal_skipped": "0",
          "rebal_failures": "0",
          "time_left": "",
          "rebal_data": "0Bytes",
          "vol_id": "998550b9-baa0-461c-8b29-98722267e9e2",
          "rebal_status": "not_started",
          "updated_at": "2017-10-16 14:53:02.915996+00:00",
          "rebal_id": "00000000-0000-0000-0000-000000000000",
          "rebal_lookedup": "0"
        },
        "f1bce092-6e5e-4ac3-88fe-134be2a17a71": {
          "rebal_data": "0Bytes",
          "rebal_id": "00000000-0000-0000-0000-000000000000",
          "rebal_status": "not_started",
          "rebal_files": "0",
          "time_left": "",
          "updated_at": "2017-10-16 14:52:45.130705+00:00",
          "rebal_lookedup": "0",
          "vol_id": "998550b9-baa0-461c-8b29-98722267e9e2",
          "hash": "495c844473354686b9f60fe4569998ca",
          "rebal_skipped": "0",
          "rebal_failures": "0"
        }
      },
      "vol_id": "998550b9-baa0-461c-8b29-98722267e9e2",
      "hash": "066a010131e05681bcb13d5494cd20b2"
    }
  ]
}
```

In Gluster, the volume is properly named:
```
# gluster volume list
volume_gama_disperse_4_plus_2x2
```

But the name is not available in etcd:
```
# etcdctl --ca-file /etc/pki/tls/certs/ca-usmqe.crt --cert-file /etc/pki/tls/certs/etcd.crt --key-file /etc/pki/tls/private/etcd.key --endpoints https://${HOSTNAME}:2379 ls /clusters/12353d78-fe6a-42dc-827a-ff887c0a2802/Volumes/998550b9-baa0-461c-8b29-98722267e9e2
/clusters/12353d78-fe6a-42dc-827a-ff887c0a2802/Volumes/998550b9-baa0-461c-8b29-98722267e9e2/RebalanceDetails
/clusters/12353d78-fe6a-42dc-827a-ff887c0a2802/Volumes/998550b9-baa0-461c-8b29-98722267e9e2/Bricks
/clusters/12353d78-fe6a-42dc-827a-ff887c0a2802/Volumes/998550b9-baa0-461c-8b29-98722267e9e2/vol_id
/clusters/12353d78-fe6a-42dc-827a-ff887c0a2802/Volumes/998550b9-baa0-461c-8b29-98722267e9e2/hash
/clusters/12353d78-fe6a-42dc-827a-ff887c0a2802/Volumes/998550b9-baa0-461c-8b29-98722267e9e2/updated_at
/clusters/12353d78-fe6a-42dc-827a-ff887c0a2802/Volumes/998550b9-baa0-461c-8b29-98722267e9e2/options
```

Packages and versions - on Tendrl server:
```
tendrl-ansible-1.5.3-20171016T090020.d9e5914.noarch
tendrl-api-1.5.3-20171013T082716.a2f3b3f.noarch
tendrl-api-httpd-1.5.3-20171013T082716.a2f3b3f.noarch
tendrl-commons-1.5.3-20171013T081843.c73101a.noarch
tendrl-grafana-plugins-1.5.3-20171016T100950.e8eb6c8.noarch
tendrl-grafana-selinux-1.5.3-20171013T090621.ffb1b7f.noarch
tendrl-monitoring-integration-1.5.3-20171016T100950.e8eb6c8.noarch
tendrl-node-agent-1.5.3-20171016T094453.4aa81f7.noarch
tendrl-notifier-1.5.3-20171011T200310.3c01717.noarch
tendrl-selinux-1.5.3-20171013T090621.ffb1b7f.noarch
tendrl-ui-1.5.3-20171016T141509.544015a.noarch
```

Packages and versions - on Storage server:
```
glusterfs-4.0dev-0.209.git067f380.el7.centos.x86_64
glusterfs-api-4.0dev-0.209.git067f380.el7.centos.x86_64
glusterfs-cli-4.0dev-0.209.git067f380.el7.centos.x86_64
glusterfs-client-xlators-4.0dev-0.209.git067f380.el7.centos.x86_64
glusterfs-events-4.0dev-0.209.git067f380.el7.centos.x86_64
glusterfs-fuse-4.0dev-0.209.git067f380.el7.centos.x86_64
glusterfs-geo-replication-4.0dev-0.209.git067f380.el7.centos.x86_64
glusterfs-libs-4.0dev-0.209.git067f380.el7.centos.x86_64
glusterfs-server-4.0dev-0.209.git067f380.el7.centos.x86_64
python2-gluster-4.0dev-0.209.git067f380.el7.centos.x86_64
tendrl-commons-1.5.3-20171013T081843.c73101a.noarch
tendrl-gluster-integration-1.5.3-20171013T082052.b8ddae5.noarch
tendrl-node-agent-1.5.3-20171016T094453.4aa81f7.noarch
tendrl-selinux-1.5.3-20171013T090621.ffb1b7f.noarch
```

I saw this issue already once, but I don't know how to reproduce. If I'll find some other information, I'll update this issue.

**Comment by shtripat** [comment] 2017-10-17 08:33
Looking at the API response, looks like volume sync is not yet done and not all the volume attributes are available yet. I would suggest to verify with etcd as well once if all the values are already present.

This might happen (as I have observed) in case the cluster import was done and first round of cluster data sync is not yet over. It might be a transient state and once all the volume details are available and cluster is marked as `managed=true` the volume details should be available properly.

**Comment by dahorak** [comment] 2017-10-17 09:07
@shtripat The cluster is running for few hours already, so there is probably some problem with the syncing process.
@mbukatov spotted the same issue now, but with no specific reproduction steps.

**Comment by shtripat** [comment] 2017-10-17 10:24
@dahorak please share the setup details for further debugging.
Also I would suggest to check `/var/log/messages` on provisioner node from storage nodes and look for `ERROR` and `Exception`.

**Comment by julienlim** [comment] 2017-10-26 12:31
@dahorak @mbukatov @shtripat I've had my deployment running for almost 24 hours, and still the volume name is missing.  I don't think data sync should take 24 hours.  My tendrl environment is based on the 1.5.3 release (which tendrl-ansible 1.5.3 is pulling from).

**Comment by shtripat** [comment] 2017-10-26 14:01
@julienlim I had tested with release branch as well. I would suspect that either gluster-integration is down on some storage nodes or some errors while cluster data sync in gluster-integration. Please share the setup detail in a mail for further debugging. In the same time you can check if gluster-integration is running on all the nodes and also check `/var/log/messages` for any errors on storage nodes.

**Comment by julienlim** [comment] 2017-10-26 16:13
@shtripat I have confirmed that gluster-integration is running on all the storage nodes.

Please advise which files/logs, etc. you would like and I can email them over to you.  Thanks.

**Comment by shtripat** [comment] 2017-11-02 09:23
@julienlim as discussed earlier over chat there are some fixes around TTL for the volumes has gone in and we need to test with latest master.

**Comment by anivargi** [comment] 2017-11-10 04:47
@shtripat is this fixed?

**Comment by shtripat** [comment] 2017-11-10 06:37
@anivargi with bigger TTL values based on no of volumes in the cluster, this should be fine.

**Comment by shtripat** [comment] 2018-02-12 03:38
Off late with latest changes we havent faced this issue at all. @r0h4n I feel we can close this.

**Comment by shtripat** [comment] 2018-03-20 04:34
Closing this as haven't seen this happening now. Can open new one if faced again.

**Closed by shtripat** 2018-03-20 04:34 UTC
Labels: backend
