### ISSUE TITLE
GetClusterList returns 500 Internal Server Error

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/api#159] opened 2017-04-27 12:29 UTC
GetClusterList returns `500 Internal Server Error` about 30 seconds after the first cluster is imported. The impoer cluster job status says finished, however it takes about 30 seconds till the `GetClusterList` starts to work and returns list with the imported cluster.

Used package:
tendrl-api-1.2.3-04_26_2017_01_51_04.noarch

**Comment by fbalak** [comment] 2017-05-03 18:03
`GetClusterList` now returns `500 Internal Server Error` right after the cluster is imported. After few seconds the service starts working as expected.
Tested with:
tendrl-api-1.2.3-05_03_2017_01_51_04.noarch
tendrl-node-agent-1.2.3-05_03_2017_00_01_04.noarch
tendrl-commons-1.2.3-05_03_2017_05_13_04.noarch

**Comment by mkudlej** [comment] 2017-05-04 08:11
I see this issue also with importing of Ceph cluster. Imported cluster should be in cluster list when job for importing has finished. There should not be internal server error.

**Comment by ltrilety** [comment] 2017-05-04 08:23
As of now it never stop to return `500 Internal Server Error`

Checked in:
tendrl-api-1.2.3-05_03_2017_01_51_04.noarch

**Comment by ltrilety** [comment] 2017-05-04 16:26
OK, so now it returns empty list. I agree that's a big improvement, however there should be no visible delay between the task is finished and the cluster is present in the list.

![empty_cluster_list](https://cloud.githubusercontent.com/assets/22369834/25713980/db1e727e-30f6-11e7-91fa-24f44ca6e1da.png)

Checked with:
tendrl-api-httpd-1.2.3-05_04_2017_01_51_04.noarch
tendrl-dashboard-1.2.3-05_04_2017_04_11_06.noarch
tendrl-performance-monitoring-1.2.3-05_04_2017_11_57_30.noarch
tendrl-api-doc-1.2.3-05_04_2017_01_51_04.noarch
tendrl-node-agent-1.2.3-05_04_2017_11_40_12.noarch
etcd-3.1.3-1.el7.x86_64
tendrl-api-1.2.3-05_04_2017_01_51_04.noarch
tendrl-commons-1.2.3-05_04_2017_05_13_04.noarch

**Comment by ltrilety** [comment] 2017-05-11 11:26
The `500 Internal Server Error` is back and now it takes even longer till the cluster appears in the list.

Checked with:
tendrl-dashboard-1.2.3-05_11_2017_04_11_05.noarch
tendrl-performance-monitoring-1.2.3-05_11_2017_03_02_05.noarch
tendrl-api-httpd-1.2.3-05_11_2017_01_51_04.noarch
tendrl-node-agent-1.2.3-05_11_2017_00_01_05.noarch
tendrl-api-doc-1.2.3-05_11_2017_01_51_04.noarch
tendrl-commons-1.2.3-05_11_2017_05_13_05.noarch
etcd-3.1.3-1.el7.x86_64
tendrl-api-1.2.3-05_11_2017_01_51_04.noarch

**Comment by r0h4n** [comment] 2017-05-17 10:19
Still investigating this one, have you seen this with latest builds btw?

**Comment by fbalak** [comment] 2017-05-17 10:25
@r0h4n I think that it worked when I imported cluster yesterday but I will test it more and close it after https://github.com/Tendrl/node-agent/issues/435 is resolved.

**Comment by ltrilety** [comment] 2017-05-18 07:00
@r0h4n Yes I can see it on:
tendrl-commons-1.2.3-05_18_2017_05_13_05.noarch
tendrl-dashboard-1.2.3-05_18_2017_04_11_06.noarch
tendrl-performance-monitoring-1.2.3-05_18_2017_03_02_04.noarch
tendrl-api-1.2.3-05_18_2017_10_45_13.noarch
tendrl-api-httpd-1.2.3-05_18_2017_10_45_13.noarch
tendrl-node-agent-1.2.3-05_18_2017_04_16_25.noarch
tendrl-api-doc-1.2.3-05_18_2017_10_45_13.noarch

**Comment by r0h4n** [comment] 2017-05-18 07:11
@anmolsachan Please try to reproduce this issue.

Problem here is that after ImportCluster succeeds, for sometime the GetClusterList API returns 500, and then it works as expected. right @ltrilety ?

@anivargi @anmolsachan This happens because all objects in the cluster arent synced very fast and due to which the API breaks

**Comment by r0h4n** [comment] 2017-05-18 07:26
@anivargi Please list out mandatory objects inside /clusters/:id/* required for a successful GetClusterList API call

**Comment by ltrilety** [comment] 2017-05-18 09:34
@r0h4n right, sometimes it doesn't return 500 but empty list. However that's not correct too.
Moreover the time when it starts to work differs. Once it is 30 seconds other time it's around 1 minute and more especially for ceph cluster.

**Comment by anmolsachan** [comment] 2017-05-18 09:45
@ltrilety Can u please elaborate on how are you checking the job status , I mean directly through etcd or the dashboard ?

**Comment by ltrilety** [comment] 2017-05-18 09:57
@anmolsachan using dashboard or api `jobs` call. I didn't check `etcd` directly.

**Comment by fbalak** [comment] 2017-05-18 11:24
I have tested it on two instances where I had 1 gluster cluster and 1 ceph cluster. After successful import of gluster cluster `GetClusterList` returns `500 Internal Server Error` but doesn't get better. This response remains for this call for more than hour.
Tested with:
tendrl-node-agent-1.2.3-05_18_2017_13_47_17.noarch
tendrl-api-1.2.3-05_18_2017_14_04_12.noarch

**Comment by anmolsachan** [comment] 2017-05-19 17:24
@r0h4n @ltrilety @fbalak I tested the latest setup with following:
tendrl-commons-1.3.0-05_19_2017_16_29_16.noarch
tendrl-node-agent-1.3.0-05_19_2017_00_01_05.noarch
tendrl-api-1.3.0-05_19_2017_01_51_03.noarch
tendrl-dashboard-1.3.0-05_19_2017_04_11_04.noarch
tendrl-api-httpd-1.3.0-05_19_2017_01_51_03.noarch

I tested the setup with a already created cluster.  Then I cleared the etcd and restarted the services.
Then I imported the cluster using a manual job using a python script. Here I did not involve api and dashboard and tested only back-end. The cluster got imported successfully and got listed under /clusters in etcd immediately .
In second scenario I tested using UI. Again cleared the etcd and restarted the services. Fired import cluster and it got imported and got listed under clusters. I did not notice any lag there.

If any of you can replicate the issue with latest release please notify as I was not able to do so.

**Comment by fbalak** [comment] 2017-05-19 17:42
@anmolsachan I am currently not able to import cluster. I will test this again after https://github.com/Tendrl/node-agent/issues/452 will be resolved.

**Comment by ltrilety** [comment] 2017-05-20 13:55
@anmolsachan I think even in our case it is immediately in etcd, but the API call `GetClustersList` doesn't return it properly.
Last time when I was trying to reproduce this issue the cluster was present in etcd, but it never shows in output from `GetClustersList`.

**Comment by anmolsachan** [comment] 2017-05-22 09:16
@fbalak @ltrilety Today I again tried import cluster with following:
tendrl-api-httpd-1.3.0-05_22_2017_01_51_04.noarch
tendrl-api-1.3.0-05_22_2017_01_51_04.noarch
tendrl-dashboard-1.3.0-05_22_2017_04_11_04.noarch
tendrl-node-agent-1.3.0-05_22_2017_00_01_06.noarch
tendrl-node-monitoring-1.3.0-05_22_2017_04_25_03.noarch
tendrl-commons-1.3.0-05_22_2017_05_13_04.noarch
tendrl-ceph-integration-1.3.0-05_21_2017_06_35_04.noarch
For my setup, the import cluster is working and GetClusterList is showing without any time delay. There are a  few related issues that are being fixed right now. I will again try to replicate this issues once those issues get fixed. Meanwhile if any of you encounters this issue again, please notify.

**Comment by anivargi** [comment] 2017-05-23 06:36
@fbalak @ltrilety please reply with your findings and exact steps if this is still a issue.

**Closed** 2017-07-21 08:52 UTC
Labels: API, backend, bug
