### ISSUE TITLE
ImportCluster API call doesn't work

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#94] opened 2017-03-08 09:29 UTC
When I call `POST` `hostname/api/1.0/ImportCluster` according to https://github.com/Tendrl/api/blob/c26f4f9b02a148b1b8793ebc14dbd6ba6fae8acd/docs/clusters.adoc I get `job_id` in response but the job is never finished. I sent json: `{"node_ids":["818072dd-d5ec-4df6-8afd-b72887625d72","aee60933-f757-4f0b-9d0f-199073660f54","cf404639-8807-48ea-9b3d-ffc8b7cb4d97","e8b5292d-052a-4ac5-9748-fb16d7125e15"],"sds_type":"gluster"}`. On storage nodes there is already created gluster trusted pool.  Job remains `new` and there is no cluster imported in tendrl. Job should finish and there should be imported cluster.

Tested with:
tendrl-api-1.2.1-03_08_2017_01_51_04.noarch
tendrl-gluster-integration-1.2.1-03_08_2017_04_38_03.noarch
tendrl-commons-1.2.1-03_08_2017_04_42_04.noarch
tendrl-node-agent-1.2.1-03_08_2017_00_01_03.noarch

**Comment by anivargi** [comment] 2017-03-08 12:18
@fbalak Can you try with `"sds_type":"glusterfs"`

**Comment by fbalak** [comment] 2017-03-08 13:18
@anivargi I tried it with `"sds_type":"glusterfs"` as you suggested but it still remains in a `new` state.

**Comment by sankarshanmukhopadhyay** [comment] 2017-03-13 06:09
@anivargi - this would need to be addressed - it is blocking testing of the build

**Comment by anivargi** [comment] 2017-03-14 05:42
@shtripat Can you please debug this? Thanks.

**Comment by shtripat** [comment] 2017-03-14 05:55
@anivargi I would start on this today.
@TimothyAsirJeyasing I remember we had discussed about a dedicated setup which always gets updated post builds and anybody from team can verify the latest builds for any failures and required fixes. I don't see any such thing till now. Why I am asking this, because every time such issues happen I need to destroy my own dev setup and do a fresh one for verification. A dedicated setup for only verification of build is for sure required.

**Comment by shtripat** [comment] 2017-03-14 08:28
@fbalak After debugging a bit I find that its a regression where few patches partially got merged in master and that why this flow is broken. Proper fixes are available in develop branch.

To make testing continue, I would suggest you to use older builds from copr (may a week older rpms, 7th march 2017).

In the mean time I would suggest @GowthamShanmugam to revert back the changes in master and make it working for master so that QE can continue testing with master RPMs. Once develop branch is stable with import flow, QE can switch to develop branch.

@r0h4n @nthomas-redhat @brainfunked plz ack.

**Comment by r0h4n** [comment] 2017-03-15 11:03
@fbalak Can you verify this bug again based on latest packages from master?

**Comment by mkudlej** [comment] 2017-03-15 13:32
This is blocked by https://github.com/Tendrl/api/issues/99

**Comment by sankarshanmukhopadhyay** [comment] 2017-03-23 08:34
The issue which this is blocked by is closed - can this now be verified?

**Comment by mkudlej** [comment] 2017-03-23 13:48
Still no luck:
```
NoMethodError - undefined method `[]' for nil:NilClass:
	/usr/share/tendrl-api/lib/tendrl/flow.rb:14:in `initialize'
	/usr/share/tendrl-api/app/controllers/nodes_controller.rb:38:in `new'
	/usr/share/tendrl-api/app/controllers/nodes_controller.rb:38:in `block in <class:NodesController>'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:945:in `forward'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1019:in `route_missing'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:980:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:945:in `forward'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1019:in `route_missing'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:980:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:945:in `forward'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1019:in `route_missing'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:980:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:945:in `forward'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1019:in `route_missing'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:980:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:945:in `forward'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1019:in `route_missing'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:980:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `call'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
10.40.3.40 - - [23/Mar/2017:13:21:15 +0000] "POST /1.0/ImportCluster HTTP/1.1" 500 30 0.0647
```
It seems to me that it is connected with https://github.com/Tendrl/commons/pull/285#issuecomment-288370228 but this is just my guess.

**Comment by mkudlej** [comment] 2017-03-31 06:21
Still there with 
```
etcd-3.1.0-2.el7.x86_64
python-etcd-0.4.3-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.2.1-03_31_2017_01_51_34.noarch
tendrl-api-doc-1.2.1-03_31_2017_01_51_34.noarch
tendrl-api-httpd-1.2.1-03_31_2017_01_51_34.noarch
tendrl-commons-1.2.1-03_31_2017_06_03_08.noarch
tendrl-dashboard-1.2.1-03_31_2017_04_11_03.noarch
tendrl-performance-monitoring-1.2.1-03_31_2017_03_02_02.noarch
```
on server and
```
centos-release-ceph-jewel-1.0-1.el7.centos.noarch
ceph-base-10.2.3-0.el7.x86_64
ceph-common-10.2.3-0.el7.x86_64
ceph-mon-10.2.3-0.el7.x86_64
ceph-selinux-10.2.3-0.el7.x86_64
libcephfs1-10.2.3-0.el7.x86_64
python-cephfs-10.2.3-0.el7.x86_64
python-etcd-0.4.3-1.noarch
tendrl-commons-1.2.1-03_31_2017_06_03_08.noarch
tendrl-node-agent-1.2.1-03_31_2017_06_35_45.noarch
tendrl-node-monitoring-1.2.1-03_31_2017_00_37_03.noarch
```
on ceph node and
```
glusterfs-3.9.1-1.el7.x86_64
glusterfs-api-3.9.1-1.el7.x86_64
glusterfs-api-devel-3.9.1-1.el7.x86_64
glusterfs-cli-3.9.1-1.el7.x86_64
glusterfs-client-xlators-3.9.1-1.el7.x86_64
glusterfs-devel-3.9.1-1.el7.x86_64
glusterfs-events-3.9.1-1.el7.x86_64
glusterfs-extra-xlators-3.9.1-1.el7.x86_64
glusterfs-fuse-3.9.1-1.el7.x86_64
glusterfs-geo-replication-3.9.1-1.el7.x86_64
glusterfs-libs-3.9.1-1.el7.x86_64
glusterfs-rdma-3.9.1-1.el7.x86_64
glusterfs-server-3.9.1-1.el7.x86_64
python-etcd-0.4.3-1.noarch
python-gluster-3.9.1-1.el7.noarch
tendrl-commons-1.2.1-03_31_2017_06_03_08.noarch
tendrl-node-agent-1.2.1-03_31_2017_06_35_45.noarch
tendrl-node-monitoring-1.2.1-03_31_2017_00_37_03.noarch
```
on gluster node.

**Comment by sankarshanmukhopadhyay** [comment] 2017-04-03 12:24
Please look at https://github.com/Tendrl/documentation/wiki/Information-required-for-debugging-issues-on-the-Tendrl-stack and help us debug this quicker by providing the information sought. Thanks for the package list in your report.

**Comment by fbalak** [comment] 2017-04-03 12:49
ImportCluster for gluster is now working (but `tendrl-gluster-integration` must be pre-installed https://github.com/Tendrl/node-agent/issues/367).
Tested with:
tendrl-api-1.2.1-04_03_2017_01_51_03.noarch
tendrl-commons-1.2.1-04_01_2017_00_59_17.noarch
tendrl-node-agent-1.2.2-04_03_2017_00_01_04.noarch
tendrl-gluster-integration-1.2.1-04_03_2017_04_38_02.noarch

**Comment by anivargi** [comment] 2017-04-04 12:56
@fbalak you need to use tendrl-api-1.2.2

**Comment by anivargi** [comment] 2017-04-04 12:57
Also can you share your curl command for both?

**Comment by fbalak** [comment] 2017-04-04 13:54
@anivargi sure, I will test it after tendrl-api-1.2.2 packages will be available in master repo. 

for gluster:
curl -XPOST -H "Content-Type: application/json" -H 'Authorization: Bearer c30b2958b68c90aeb350b44e96975cce26b11a4ccdaedf421a4cf19b35ec3989' -d '{ "node_ids": ["c6d91db2-d524-4d8b-a81f-dff0b5d337ca", "c3dbde48-1fd2-406c-877d-32ed21887162", "526758ba-ced3-4390-bb0d-b38ecc9ea449", "cfff3b58-d7c3-49ed-ab38-8f241375cf15"], "sds_type":"glusterfs"}' http://hostname/api/1.0/ImportCluster where hostname is address of node with server

for ceph
curl -XPOST -H "Content-Type: application/json" -H 'Authorization: Bearer c30b2958b68c90aeb350b44e96975cce26b11a4ccdaedf421a4cf19b35ec3989' -d '{ "node_ids": list_of_ceph_nodes, "sds_type":"ceph"}' http://hostname/api/1.0/ImportCluster

**Comment by sankarshanmukhopadhyay** [comment] 2017-04-05 15:27
The packages are now available. Please provide feedback once you get to them to run this section of the test.

**Comment by mkudlej** [comment] 2017-04-06 16:18
I've tested this for import ceph cluster and it works. Problem was that Epel should be enabled even after Tendrl installation because tendrl-ceph-integration package has dependency from epel.
Tested with:
```
centos-release-ceph-jewel-1.0-1.el7.centos.noarch
ceph-base-10.2.3-0.el7.x86_64
ceph-common-10.2.3-0.el7.x86_64
ceph-mon-10.2.3-0.el7.x86_64
ceph-selinux-10.2.3-0.el7.x86_64
libcephfs1-10.2.3-0.el7.x86_64
python-cephfs-10.2.3-0.el7.x86_64
tendrl-ceph-integration-1.2.2-04_06_2017_10_49_05.noarch
tendrl-commons-1.2.2-04_06_2017_04_42_05.noarch
tendrl-node-agent-1.2.2-04_06_2017_00_01_33.noarch
tendrl-node-monitoring-1.2.2-04_06_2017_00_37_03.noarch
```

**Comment by mkudlej** [comment] 2017-04-06 16:18
@fbalak Please close this.

**Closed** 2017-04-07 07:03 UTC
Labels: backend, needs attention
